### ISSUE TITLE
Localization: specific string

### ISSUE THREAD

**Issue by coresh** [sirugh/translatotron#4]
`en_US.csv` a string example:
```
"Please remove invalid characters: {0}.", "Please remove invalid characters: {0}."
```
provides with the issue:
```
Generating new i18n for en_US.csv at /tmp/translatotron/generated/en_US.json
/tmp/translatotron/node_modules/csv-parse/lib/sync.js:21
  if(err1 !== undefined) throw err1
                         ^

CsvError: Invalid Opening Quote: a quote is found inside a field at line 103
    at Parser.__parse (/tmp/translatotron/node_modules/csv-parse/lib/index.js:619:19)
    at module.exports (/tmp/translatotron/node_modules/csv-parse/lib/sync.js:20:23)
    at /tmp/translatotron/src/index.js:78:29
    at Array.forEach (<anonymous>)
    at /tmp/translatotron/src/index.js:63:9
    at FSReqCallback.oncomplete (fs.js:171:23) {
  code: 'INVALID_OPENING_QUOTE',
  column: 'value',
  empty_lines: 0,
  error: undefined,
  header: false,
  index: 1,
  invalid_field_length: 0,
  quoting: false,
  lines: 103,
  records: 102,
  field: ' '
}

```

```
node src/index.js
```
```
node --version
v14.15.4
```

Thank you for a quick fix

**Comment by coresh** [comment]
Note: the issue -> related to the existed `space`:

no issue example:
```
"text","text"
```
issue example (space - after comma):
```
"text", "text"
```

**Comment by sirugh** [comment]
Would you be able to provide a fix? I'd welcome a contribution :)

**Comment by coresh** [comment]
Re:
```
Would you be able to provide a fix? I'd welcome a contribution :)
```
Done.

[Pull requiest: https://github.com/sirugh/translatotron/pull/5](https://github.com/sirugh/translatotron/pull/5)

Note:

Appended fix related to multiple csv columns issue.

E.g:
2 columns and 4 columns:
```
"Text","Text"
"Text","Text",module,Magento_Customer
```

Thank you
